GO_ENV = "test"

PORT = 8000

COOKIE_NAME="rds-session-testing"

PUBLIC_KEY = '''-----BEGIN PUBLIC KEY-----
MIGeMA0GCSqGSIb3DQEBAQUAA4GMADCBiAKBgHo6sGbw8qk+XU9sBVa4w2aEq01i
oKDMFFQa9mPy0MRScTCsrfEjbypD4VqIjJcwXGmDWKVhMcJ8SMZuJumIJ10vU9ca
WSh/aHhAxiOIqOEe54IyYTwjcn5avdZry3zl62RYQ7tDZCPAR/WvFCIkgRXwjXfC
Xpm4LR6ynKDMvsDNAgMBAAE=
-----END PUBLIC KEY-----'''